import type { DeviceConfig, DeviceType } from "../types/devices.type";

export const DEVICES: Record<DeviceType, DeviceConfig> = {
  "iphone-15": {
    label: 'iPhone 15',
    width: 393,
    height: 852,
    borderRadius: 48,
    notch: true,
  },
  "iphone-14": {
    label: 'iPhone 14',
    width: 390,
    height: 844,
    borderRadius: 47,
    notch: true,
  },
  "iphone-13": {
    label: 'iPhone 13',
    width: 390,
    height: 844,
    borderRadius: 47,
    notch: true,
  },
  "iphone-12": {
    label: 'iPhone 12',
    width: 390,
    height: 844,
    borderRadius: 47,
    notch: true,
  },
  "iphone-11": {
    label: 'iPhone 11',
    width: 414,
    height: 896,
    borderRadius: 44,
    notch: true,
  },
  "iphone-x": {
    label: 'iPhone X',
    width: 375,
    height: 812,
    borderRadius: 40,
    notch: true,
  },
  "iphone-8": {
    label: 'iPhone 8',
    width: 375,
    height: 667,
    borderRadius: 28,
    notch: false,
  },
  "iphone-7": {
    label: 'iPhone 7',
    width: 375,
    height: 667,
    borderRadius: 28,
    notch: false,
  },
  "iphone-se": {
    label: 'iPhone SE',
    width: 320,
    height: 568,
    borderRadius: 24,
    notch: false,
  },

  android: {
    label: 'Android (Pixel)',
    width: 412,
    height: 892,
    borderRadius: 36,
    notch: false,
  },
  "galaxy-s23": {
    label: 'Galaxy S23',
    width: 393,
    height: 873,
    borderRadius: 36,
    notch: true,
  },
  "galaxy-s22": {
    label: 'Galaxy S22',
    width: 360,
    height: 780,
    borderRadius: 34,
    notch: true,
  },
  "galaxy-s21": {
    label: 'Galaxy S21',
    width: 360,
    height: 800,
    borderRadius: 34,
    notch: true,
  },
  "galaxy-s20": {
    label: 'Galaxy S20',
    width: 360,
    height: 800,
    borderRadius: 34,
    notch: true,
  },
  "galaxy-note20": {
    label: 'Galaxy Note 20',
    width: 412,
    height: 915,
    borderRadius: 30,
    notch: true,
  },
  "galaxy-note10": {
    label: 'Galaxy Note 10',
    width: 412,
    height: 869,
    borderRadius: 30,
    notch: true,
  },
  "galaxy-a52": {
    label: 'Galaxy A52',
    width: 384,
    height: 854,
    borderRadius: 30,
    notch: true,
  },
  tablet: {
    label: 'iPad',
    width: 820,
    height: 1180,
    borderRadius: 20,
    notch: false,
  },
  "ipad-pro-12.9": {
    label: 'iPad Pro 12.9"',
    width: 1024,
    height: 1366,
    borderRadius: 18,
    notch: false,
  },
  "ipad-pro-11": {
    label: 'iPad Pro 11"',
    width: 834,
    height: 1194,
    borderRadius: 18,
    notch: false,
  },
  "ipad-air": {
    label: 'iPad Air',
    width: 820,
    height: 1180,
    borderRadius: 18,
    notch: false,
  },
  "ipad-mini": {
    label: 'iPad Mini',
    width: 744,
    height: 1133,
    borderRadius: 16,
    notch: false,
  },

}